### PR TITLE
ci: add semantic-release to publish packages

### PR DESCRIPTION
**Pull request by jmcdo29**

### CODE REVIEW

**Comment by jmcdo29** [comment]
@kamilmysliwiec this should set up releases every time a commit is made to `master` with `fix` or `feat` in the subject, and will bump the package accordingly. Let me know if you'd like anything else

**Comment by kamilmysliwiec** [comment]
Great @jmcdo29! I'm not fully sure whether the GITHUB_TOKEN is required, you sure about this one? I believe anyone with write access should be able to commit & create a tag if needed.

**Comment by jmcdo29** [comment]
@kamilmysliwiec this is from the recipe from the semantic-release GitHub repository. It's probably fine either way, but all GitHub Actions have access to `GITHUB_TOKEN`

**Comment by kamilmysliwiec** [comment]
I've added the `NPM_TOKEN` to secrets already so we should be good to merge :)

**Review by kamilmysliwiec — APPROVED** [review]

**Pull request merged**
