### PR TITLE
Add example for throttler behind a proxy

### PR DESCRIPTION
**Pull request by bttger**

### CODE REVIEW

**Comment by jmcdo29** [comment]
This looks like a great addition! Would you like to add it [to the docs as well](https://github.com/nestjs/docs.nestjs.com)?

**Comment by bttger** [comment]
Yes, I'll make a PR later :)

**Comment by bttger** [comment]
Just found out that the example also works with fastify.

**Comment by bttger** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/2045

**Pull request merged**
